name: Daily Streak Maintainer

on:
  schedule:
    - cron: '0 12 * * *'  # every day at 12:00 UTC
  workflow_dispatch:

jobs:
  streak:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Commit streak update
        run: |
          echo "$(date '+%Y-%m-%d %H:%M:%S') - keeping the streak alive" >> streak-log.txt
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add streak-log.txt
          git commit -m "✅ Automated streak update: $(date '+%Y-%m-%d')"
          git push
