name: Streak Maintainer

on:
  schedule:
    - cron: '0 18 * * *'   # Runs every day at 12:00 AM BD Time (UTC+6)
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-streak:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Git identity
        run: |
          git config --global user.name 'ZeroHack01'
          git config --global user.email 'mongwoiching2080@gmail.com'

      - name: Update streak log
        run: |
          echo "# Streak Log" > streak-log.md
          echo "Daily log to maintain GitHub contribution streak for ZeroHack01" >> streak-log.md
          echo "$(date +'%Y-%m-%d'): Streak maintained by ZeroHack01" >> streak-log.md

      - name: Commit and push
        run: |
          git add streak-log.md
          git commit -m "Auto-update streak log for $(date +'%Y-%m-%d')" || echo "Nothing to commit"
          git push
