name: Daily Streak Maintainer

on:
  schedule:
    - cron: '0 4 * * *'  # Every day at 4 AM UTC
  workflow_dispatch:

jobs:
  update-streak:
    runs-on: ubuntu-latest
    env:
      GIT_AUTHOR_NAME: ZeroHack01
      GIT_AUTHOR_EMAIL: mongwoiching2080@gmail.com
      GIT_COMMITTER_NAME: ZeroHack01
      GIT_COMMITTER_EMAIL: mongwoiching2080@gmail.com

    steps:
      - uses: actions/checkout@v3

      - name: Update streak log
        run: |
          echo "$(date '+%Y-%m-%d %H:%M:%S') - Keeping the streak alive" >> streak-log.md
          git add streak-log.md
          if [[ -n "$(git diff --cached --quiet; echo $?)" ]]; then
            git commit -m "✅ Streak update: $(date '+%Y-%m-%d')"
            git push
          else
            echo "No changes detected. Skipping commit."
          fi
