name: Daily Streak Maintainer

on:
  schedule:
    - cron: '0 4 * * *' # Runs daily at 4 AM UTC
  workflow_dispatch:

jobs:
  update-streak:
    runs-on: ubuntu-latest
    env:
      GIT_AUTHOR_NAME: ZeroHack01
      GIT_AUTHOR_EMAIL: mongwoiching2080@gmail.com
      GIT_COMMITTER_NAME: ZeroHack01
      GIT_COMMITTER_EMAIL: mongwoiching2080@gmail.com

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git identity
        run: |
          git config --local user.name "$GIT_AUTHOR_NAME"
          git config --local user.email "$GIT_AUTHOR_EMAIL"

      - name: Update streak log
        run: |
          DATE=$(date '+%Y-%m-%d')
          TIME=$(date '+%H:%M:%S')

          if [ ! -s streak-log.md ]; then
            echo "# 📅 Commit Streak Log" > streak-log.md
            echo "" >> streak-log.md
            echo "- $DATE $TIME – Initialized" >> streak-log.md
          else
            echo "- $DATE $TIME – Keeping the streak alive 🔥" >> streak-log.md
          fi

          git add streak-log.md

          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 78
          else
            git commit -m "✅ Streak update: $DATE"
            git remote set-url origin https://x-access-token:${{ secrets.PERSONAL_TOKEN }}@github.com/ZeroHack01/StreakHelper.git
            git push
          fi

      - name: Show status
        if: always()
        run: |
          echo "Workflow finished with status: ${{ job.status }}"
